### ISSUE TITLE
Always disable master file search

### ISSUE THREAD

**Issue by martinb3** [thomasjo/atom-latex#109]
Hello! I just downloaded this package for the first time, and thank you for all of your hard work on it! I know open source can be thankless work sometimes :)

I'd like to suggest that the 'master file search' feature _always_ be disabled by default. I guess the package decided I needed master file search when I first installed it, and it was very confusing that I opened a file, hit build, and it built a different file. I think the default/naive behavior should probably be to build the file currently open.

Since master files and child tex files are going to be a less common case, I think the user should have to explicitly enable this feature via the settings. I saw you are planning a more guided 'first startup' and better autodetection features in the future, but for now, I think the default behavior should be to disable the master file search. Perhaps in the future you can say something like, "I noticed your document doesn't have a documentclass, would you like...."

Thanks!

**Comment by thomasjo** [comment]
Thanks for the feedback. I completely understand, and I agree. Although I'm a little bit reluctant about changing this default since it's been enabled by default for such a long time, and Atom packages currently have no way of surfacing a changelog upon package update. I'll mull this one over for a few days before I make a decision. Leaning towards following your suggestion though.

**Comment by martinb3** [comment]
Cheers!

**Comment by thomasjo** [comment]
@martinb3 Sorry this ended up being forgotten, but better late than never I guess. This change will go live in the next release of the package.
