### ISSUE TITLE
Master file search

### ISSUE THREAD

**Issue by skychan** [thomasjo/atom-latex#120]
% !TEX root = main.tex

works only if there is nothing else write before, like

    % !Mode:: "TeX:UTF-8"
    % !TEX root = main.tex

will not work.

Child file cannot read the reference database that if I cite something in child file (*.bib is loaded in master file), it says "No citations found".

Thank you for this package.

**Comment by thomasjo** [comment]
I'm currently on vacation. Will investigate and respond to this properly once I return. Apologies!

**Comment by thomasjo** [comment]
Yeah, this is only currently supported if the magic comment is on the very first line. I can't remember exactly why I settled on that, but most likely due to keeping things simple. I propose that as long as the root file marker is present in a file's leading comments, it should be treated just as if it's the very first line of the file (as is required right now).

**Comment by thomasjo** [comment]
This was resolved as part of #131.

**Comment by skychan** [comment]
@thomasjo 
Cool~
thx :+1:
