### ISSUE TITLE
TeXification failed with status code 12

### ISSUE THREAD

**Issue by 5y** [thomasjo/atom-latex#146]
I try to build .tex file and get this **error **:
**TeXification failed with status code 12**

**Comment by thomasjo** [comment]
I'm going to need some addition information from you;
  1. OS and version
  2. TeX distribution; TeX Live [this covers MacTeX] or MiKTeX, including version
    1. Which builder are you using if you're using MiKTeX; latexmk or texify?
      1. If you're using MiKTeX and latexmk, do you have a functional Perl installation, which is also included in your `Path` environment variable?
  3. Are you able to build the .tex file in question from a terminal by invoking `latexmk` (or `texify` if you're using MiKTeX)?

**Comment by 5y** [comment]
1- Manjaro  3.16.7.9-1(Arch).
2- TeX Live lastest version, 
    a - Latexmk
    b- /usr/bin/latexmk
3- latex: error while loading shared libraries: libpoppler.so.55: cannot open shared object file: No such file or directory [bug](https://bugs.archlinux.org/task/16427)

**Comment by m0nhawk** [comment]
@5y Install the `poppler` package (at least it's named so in Arch).

**Comment by 5y** [comment]
It Solved with Install Poppler.
sudo pacman -S poppler-qt5 poppler-qt4  poppler-glib 
 
Thank you.

**Comment by thomasjo** [comment]
@5y Thanks for the update! I'm closing this since it seems like you resolved your problem :smile:

**Comment by Gloix** [comment]
Hi, I've been having this error code 12 lately using `latexmk` on Windows and found out that it was due to "not properly using" a comma in an author reference inside a `.bib` file.

Turns out commas are supposed to be used ONLY for naming someone as <LastName>,<FirstName>. Any other uses of commas will get you an error code 12 and the generated log file is no different from the one you'd get by properly writing the authors and succesfully compiling (diff'd them), so there's no way you can know where the mistake is (yes, I had to locate the mistake by binary searching it).

I know this issue is most probably latexmk related but since there will be people coming here seeking information, well here's a case where things can go wrong without actually telling you the mistake.

Maybe there's a flag that will make latexmk print out this error(?)

**Comment by thomasjo** [comment]
> Maybe there's a flag that will make latexmk print out this error(?)

Not to my knowledge, but if you find something, please us know!

**Comment by zhuzhikun15973** [comment]
I also got this problem on Mac, and it turns out to be that I referenced the same article multiple times in .bib file.
