### ISSUE TITLE
Cannot file the correct file to compile

### ISSUE THREAD

**Issue by Harvey-Lu** [thomasjo/atom-latex#153]
I notice that if there are multiple `.tex` files in the same directory, the package may not compile the current file I opened in atom. It maybe compile the file with the latest modified time, or something like that. Can you fix this bug to let the package compile exactly the file in my activated window in Atom? Thanks

**Comment by thomasjo** [comment]
I'm 99% sure you're seeing the *Master File Search* functionality. Simply disable that feature;

<img width="464" alt="settings_-__users_thomasjo_uni_-_atom" src="https://cloud.githubusercontent.com/assets/3622/11402226/0a937dc8-9397-11e5-8aea-46e126e59480.png">

This is enabled by default (although that might change in the near future), and it works by searching for a document within the same folder that includes the current file. If such a "master file" is found, it is built instead of the current file.

If unchecking the option does not resolve what you're seeing, then you'll need to re-open this issue and provide more details (e.g. a minimal example that reproduces the problem, as well as information about OS and TeX distribution).
