### ISSUE TITLE
TeXification failed with status code 2

### ISSUE THREAD

**Issue by arewm** [thomasjo/atom-latex#233]
For an unrelated reason, I have recently re-installed my entire computer. 

I tried to get atom-latex working, but when I try to build a project, I get a LaTeX compilation error with no log file generated. The dev console only shows the error:

> undefined:: TeXification failed with status code 2

When I try to build the file from the terminal with `pdflatex myfile.tex`, it works fine.

I cannot figure out what is causing the issue, so any advice would be welcome!

I am on a mac (macOS Sierra) with mactex-20160603 freshly installed.

**Comment by yitzchak** [comment]
atom-latex depends on `latexmk`. Can you try `latexmk -pdf myfile.tex` in the terminal?

**Comment by arewm** [comment]
It looks like it is an issue with that. I get

> Latexmk: This is Latexmk, John Collins, 22 April 2016, version: 4.45.
> Insecure dependency in open while running setgid at /Library/TeX/texbin/latexmk line 2722.

And no log file is created. 

    osx$ setgid
    -bash: setgid: command not found

If `setgid` is supposed to be a command in osx, I am not sure how it got removed or how to re-create it.

**Comment by arewm** [comment]
I realized that I installed `xcode` but not the developer tools. I thought this was the issue, but after running

    $ xcode-select --install

my problem still exists. Will try a restart and update if fixed.

**Comment by yitzchak** [comment]
I am not a Mac user so I have very little experience there, but I will try. :wink: 

I think the problem is due to Perl's security model. It could be that the `setuid` or `setgid` flag is set on 'latexmk'. Can you try the following?

```bash
stat /usr/local/texlive/2016/texmf-dist/scripts/latexmk/latexmk.pl
```

You should see something like:

```
  File: '/usr/local/texlive/2016/texmf-dist/scripts/latexmk/latexmk.pl'
  Size: 352510    	Blocks: 696        IO Block: 4096   regular file
Device: 806h/2054d	Inode: 6702567     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-06-07 14:42:51.198346588 -0400
Modify: 2016-05-02 19:56:30.000000000 -0400
Change: 2016-06-07 14:42:51.198346588 -0400
 Birth: -
```

To remove the `setuid` flag you will need to run:

```bash
chmod u-s /usr/local/texlive/2016/texmf-dist/scripts/latexmk/latexmk.pl
```

To remove the `setgid` flag you will need to run:

```bash
chmod g-s /usr/local/texlive/2016/texmf-dist/scripts/latexmk/latexmk.pl
```

You may need to execute those commands with `sudo`.

**Comment by arewm** [comment]
No luck still. Output from `stat` (in a much uglier format):

    $ stat /usr/local/texlive/2016/texmf-dist/scripts/latexmk/latexmk.pl
    16777220 4147855 -rwxr-xr-x 1 root wheel 0 352510 "Sep 29 08:28:51 2016" "May  2 19:56:30 2016" "Sep 29 01:11:46 2016" "May  2 19:56:30 2016" 4096 696 0 /usr/local/texlive/2016/texmf-dist/scripts/latexmk/latexmk.pl

I tried to remove `setuid` and `setguid` from the file, but that did not work either.

I would not normally be a mac user, but I did not purchase the computer, I consider myself a non-windows user  😁.

**Comment by arewm** [comment]
I searched for the `setgid` command and did not find anything.

    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacO>SX.sdk/usr/share/man/man2/setgid.2
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/share/ri/2.0.0/system/File/setgid%3f-c.ri
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/share/ri/2.0.0/system/File/Stat/setgid%3f-i.ri
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/share/ri/2.0.0/system/FileTest/setgid%3f-i.ri
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/share/ri/2.0.0/system/Pathname/setgid%3f-i.ri
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/share/ri/2.0.0/system/Process/Sys/setgid-c.ri
    /Users/foo/.vim_runtime/temp_dirs/undodir/%Users%foo%Downloads%latexmk%setgid
    /usr/local/Cellar/go/1.7.1/libexec/misc/cgo/test/setgid_linux.go
    /usr/share/man/man2/setgid.2

I can, however, view the manpages for `setgid`.

**Comment by thomasjo** [comment]
`setgid` and `setuid` (et al.) are system API functions, not executables. They are defined in `unistd.h`. They control file permissions. In other words, they set permission bits on files.

The error here is coming from the Perl interpreter because it detects that the `latexmk.pl` script (or one of its dependencies) has _group_ privileges and is thus "insecure". Either the MacTeX version of TeX Live has done something wrong during setup, or you have changed some permissions post-install by invoking e.g. `sudo chmod g+<flag> <path>`.

Unfortunately I haven't got time right now to setup a VM to reproduce this. Either try reinstalling MacTeX, or uninstall it and install pure TeX Live, which does not have this problem.

**Comment by arewm** [comment]
Thanks to both of you. I know that this is an issue with my setup, so I will try to figure out where the issue is coming from.

The issue is probably with a dependency on one of the packages I installed through homebrew.

**Comment by arewm** [comment]
For anyone else that might run into the issue in the future...

As  stated, the issue was that the setgid state was set for some files needed for the latexmk script. To find all of the files that had the bit set, I used the command

    find / -perm -02000 -ls > search_out

on OSX. There were a lot of results, but I found one that had to do with Tex.

**Comment by thomasjo** [comment]
@arewm Thanks for the detailed follow-up! 🙇
