### ISSUE TITLE
Preview.app not opening

### ISSUE THREAD

**Issue by cbrnr** [thomasjo/atom-latex#242]
When using the default settings (i.e. `/Applications/Preview.app` in the field for "Custom PDF Viewer Path"), no viewer application is launched and I get the following error in the log:

    An error occured while trying to run opener (126)

(BTW, it should be spelled "occurred")

However, if I put `open` in this option field, the default viewer opens fine (which is Preview.app by default).

**Comment by cbrnr** [comment]
Also, when I install Skim, the plugin doesn't find the app. Maybe there's something wrong with the default paths (e.g. maybe specifying the path is not enough but the executable within the .app folder is required)?

**Comment by thomasjo** [comment]
Specifiying a path to a `.app` bundle in the *Custom PDF Viewer Path* option is not going to work, since it expects an executable. One option that should work is to specify `open -a /Applications/Preview.app`. Note that we have support for Preview.app out of the box. It is used by default (on macOS) when Skim is not installed/found.

What path are you specifying for Skim? The default is `/Applications/Skim.app`.

**Comment by cbrnr** [comment]
Alright, thanks for the `open -a` tip! Anyway, I now reset all plugin options to their defaults, closed and opened Atom again, and now both Preview.app and Skim.app (if installed) are working correctly.
