### ISSUE TITLE
Not building: "latexmk: Bad command line arguments"

### ISSUE THREAD

**Issue by yourfriendgerasim** [thomasjo/atom-latex#243]
Just tried to use atom-latex for the first time. Building documents fails with the error message: `latexmk: Bad command line arguments` in the "LaTeX Log" on the bottom of the Atom screen. Package settings are left default. 

I'm on Windows 7, MiKTeX 2.9, Atom 1.10.2, atom-latex 0.37.0, latexmk 4.22d.

`latexmk` run from a command prompt works just normal. 

Any ideas?

**Comment by yitzchak** [comment]
Can you please verify that the latexmk version is indeed 4.22d? If so you probably need to upgrade since 4.22d was released in 2011. There was a whole bunch of options added in 4.31 include LaTeX passthrough options.

[Latexmk: current and previous versions](http://personal.psu.edu/jcc8/software/latexmk-jcc/versions.html)

**Comment by yourfriendgerasim** [comment]
Yes, it is indeed that version. 

    >latexmk -v
    Latexmk, John Collins, 26 January 2011. Version 4.22d

I will ask my admin for an upgrade and report if that fixes the issue.

**Comment by yitzchak** [comment]
@yourfriendgerasim Any luck?

**Comment by yitzchak** [comment]
Closing due to known issues with old versions of `latexmk`. Will all check for version.

**Comment by yourfriendgerasim** [comment]
Upgrading fixed the issue.

**Comment by yitzchak** [comment]
@yourfriendgerasim Awesome. I'm glad it's fixed.

**Comment by RanSaSK** [comment]
So how did you finally solve your problem? I have the same problem. I'm curious.
