### ISSUE TITLE
Config file in addition to magic comments

### ISSUE THREAD

**Issue by jrfaller** [thomasjo/atom-latex#305]
Hi there, and thanks for all the hard work on this very useful extension.

I was wondering, would it be possible to set up a configuration mechanism using a config file (for instance a .latex.json inside the folder) in addition to magic comments. I know it is a pain to implement but this would be a very good thing for two reasons:

- magic comments are verbose and take space inside the latex documents this is boring, especially for users using editors not compatible with them,
- magic comments are necessarily shared as they are located in the tex files, but it is very common that users want a special behavior for a particular machine therefore a seprated config file would be better suited.

So please consider making this possible ;)

Best regards!

**Comment by thomasjo** [comment]
This is certainly something we can consider adding in the not too distant future.

**Comment by yitzchak** [comment]
@jrfaller This feature has been added and will be in the next version.

**Comment by jrfaller** [comment]
awesome! thanks a lot I can't wait to try it!

**Comment by yitzchak** [comment]
@jrfaller It has been released.

Please note that we decided to use [YAML](http://yaml.org) instead of JSON. We also decided to use the same base name as the root document versus something like `.latex.yaml`. In other words, the settings for `foo.tex` will be in `foo.yaml`. Some very preliminary documentation is at [Overridding Build Settings](https://github.com/thomasjo/atom-latex/wiki/Overridding-Build-Settings).
