### ISSUE TITLE
LaTeX build failed

### ISSUE THREAD

**Issue by mateddy** [thomasjo/atom-latex#327]
On Windows 10, atom 1.13.0-beta8 ia32, texlive 2016 (texlive working with "pdflatex small2e")

In atom, when I choose "build", I got the following error message:
TeXification failed with status code 1 and output of "latexmk: The script engine could not be found. latexmk: Data: scriptEngine="perl.exe" "
Parsing of log files failed.

I have no cygwin and no perl installed (except the one in texlive).  Anything that I could do?

**Comment by mateddy** [comment]
When I choose "check runtime", I got the following error message:

Rscript check failed with code 1 and response of "'Rscript' is not recognized as an internal or external command, operable program or batch file. ".

**Comment by yitzchak** [comment]
Sounds like a problem with your TeX Live install. I would reinstall latexmk using the package manager then try running `latexmk -v` from command line.

**Comment by wilhamilton** [comment]
I was getting the same issue, but with MiKTeX.  

When installing latexmk through MiKTeX, the perl file was being placed at:
`scripts/latexmk/latexmk.pl` 
but atom-latex was looking for the script at `scripts/latexmk/perl/latexmk.pl`

I manually created the perl sub-directory (and moved latexmk.pl there) and got it working.  It has since stopped working (I believe due to a different non-related issue).

I'm using MiKTeX 2.9 under Windows 7.

**Comment by yitzchak** [comment]
@wilhamilton The MiKTeX bug is [here](https://sourceforge.net/p/miktex/bugs/2537/), btw.

**Comment by mateddy** [comment]
@yitzchak Yes I reinstalled latexmk and problem fixed.  Thank you very much!

**Comment by yitzchak** [comment]
Awesome! Glad we got it fixed.

Happy LaTeXing!

**Comment by babycamel** [comment]
I have the same issue on Windows 10, path is set correctly but it is still failing.

**Comment by hcsoso** [comment]
Same issue on Windows 10.
