### ISSUE TITLE
Support for .Rmd Files

### ISSUE THREAD

**Issue by jfiksel** [thomasjo/atom-latex#346]
This is an awesome package! Any plans for knitting .Rmd files? I think that would attracting a lot of R users.

**Comment by yitzchak** [comment]
Thanks for the feature request! We will look into it.

**Comment by jfiksel** [comment]
I've already done a very basic hack that's somewhat working on my system--I think it just requires extending what you do for sweave files by finding files with a .Rmd extension, using rmarkdown::render instead of knit, and then not sending any more commands to latex. Would be happy to talk more

**Comment by yitzchak** [comment]
After `rmarkdown::render` is called the document gets handed off to pandoc? Is that correct?

**Comment by jfiksel** [comment]
Correct--so the args for execRscript would just be 
 `-e "rmarkdown::render('${escapePath(jobState.getKnitrFilePath())}')"`

And then you could open the produced pdf as usual. Haven't thought about how to handle html outputs though

**Comment by jfiksel** [comment]
I also added the following in the args
```
`-e "mypdf <- gsub('.Rmd', '.pdf', '${escapePath(jobState.getKnitrFilePath())}')"`,
`-e "mystring <- paste('open', mypdf)"`,
`-e "system(mystring)"`
```

which actually opens up the pdf through an R command

**Comment by thomasjo** [comment]
While adding this wouldn't be too problematic, I'm not really keen on adding it. The reason is simply that this package exists to simplify the process of building LaTeX documents from within Atom. Adding support for Markdown files feels like a slippery slope.

As I see it, there are two viable options; we either add some sort of extensibility hook that would allow a user provided function or third-party package to provide the necessary code for this, or someone creates an entirely new package designed solely for working with Sweave/knitr files. Perhaps the sweet spot is a bit of both.

Regardless, since adding Markdown support to this package is not something that we should do, I will close this issue. We can keep discussing alternative approaches to implement this here though.
