### ISSUE TITLE
Sumatra PDF viewer cannot be invoked 

### ISSUE THREAD

**Issue by garylavayou** [thomasjo/atom-latex#405]
Currently, when I successfully compile the source `TEX `file into `PDF ` file, no PDF viewer will be opened for it.
If I click the PDF file in the output folder in _atom_, it seems will open the _pdf-view_ plugin.

I have installed the _Sumatra PDF viewer_, and have its path added to the system path variables.
And this _latex_ package provide the option to set the path of _Sumatra_, why it cannot be invoked after PDF file is successfully created?

**Comment by yitzchak** [comment]
In order to use SumatraPDF you need to put the complete path to the executable in the field `SumatraPDF Path` in the `latex` settings page. If you installed the 64bit version the default path will not work as it is the path to the 32bit executable. After you have configured the path you should have `Open Result after Successful Build` enabled and the opener set to `sumatra`.

**Comment by garylavayou** [comment]
@yitzchak Thanks. Because I only add the path of folder that contains the executable, it cannot work. After adding the complete path of the executable to `SumatraPDF Path`, it will work. Besides, since I install `SumatraPDF` in local disk D, so I must set the path by myself, no matter it is 32bit or 64bit.
