### ISSUE TITLE
Ctrl+Alt+S to view pdf doesn't work with DiCy

### ISSUE THREAD

**Issue by trentks** [thomasjo/atom-latex#428]
Just switched to DiCy to use pweave, it breaks the ctrl+alt+s functionality to view the pdf. If you spam ctrl+alt+s it seems to issue a build command (as it complains about a build currently being in progress).

I guess it's potentially relevant that I'm using Okular.

**Comment by yitzchak** [comment]
Thanks for reporting the issue!

Unfortunately, SyncTeX functionality is not available with Pweave because Pweave does not generate a source map. Sync is available in pure LaTeX documents and to a limited extent in knitr documents since knitr generates a concordance file which is then used to patch the SyncTeX file. Requesting a sync causes a `load` command to be sent to DiCy, which triggers the build spinner.

We probably could use some document explaining what functionality is available.

**Comment by trentks** [comment]
Thanks for the explanation, makes sense. Perhaps a sane default of literally just opening up the PDF even if you can't browse to the relevant portion?

**Comment by yitzchak** [comment]
This should be the current functionality. If it isn't working that way, then something is wrong.

Try doing a rebuild in case the cache has be damaged. If that doesn't work then try reloading Atom before you do the rebuild.
