### ISSUE TITLE
Problem with -shell-escape

### ISSUE THREAD

**Issue by epsilonxe** [thomasjo/atom-latex#456]
I use `minted` package in my LaTeX document.
Of course `pygmentize` is already installed and can be called in system wide.

When I typeset the document by atom-latex plugin with `Shell Escape` option enabled, it produces the error saying that `pygmentize` not installed.
However I can typeset the document with the command
```sh
$ pdflatex -shell-escape -interaction=nonstopmode the_file_name
```
successfully.

Please check this issue. Thank you.

**Comment by thomasjo** [comment]
We'll need some additional information here to help you track down the problem. First of all, what OS are you running? It looks like `pygmentize` is available via `PATH` lookup from your shell, but it might be that the necessary environment variables are not available in Atom; what's the output of `which pygmentize`? If you're using pyenv or similar, is the Python you've installed Pygments in, the global default? If not, it most likely will not be available when you run Atom, but will be available in your shell due to pyenv shims and `PATH` manipulation.

**Comment by eborkowski** [comment]
I would also be very happy to reopen this issue. Is there a solution?
