### ISSUE TITLE
Path not found

### ISSUE THREAD

**Issue by swiftsword94** [thomasjo/atom-latex#475]
I think the path isn't properly binding somewhere.
I found something similar [here](https://github.com/steelbrain/linter/issues/150)

The error I receive is :
spawn pdflatex ENOENT

and the build log is:
> pdflatex -synctex=1 -interaction=nonstopmode -file-line-error somefile

How to produce error:
1. open atom using taskbar icon
2. make a basic tex file like:

\documentclass{article}
\begin{document}
  Hello World!
\end{document}

3. try to build

I later tested this by opening atom from the command line and it started building correctly

**Comment by thomasjo** [comment]
@swiftsword94 Sorry about the late response, but are you sure you are using this package (which is called `latex` in Atom) and not the `atom-latex` package? What confuses me is the build log you show, since this package only invokes `latexmk` directly, so there should be nothing akin to `spawn pdflatex ENOENT` showing up anywhere.
