### ISSUE TITLE
Synctex inverse search problems and related issues

### ISSUE THREAD

**Issue by johanbluecreek** [thomasjo/atom-latex#481]
Hi,

I'm trying to get synctex up and running properly. Currently I'm trying to use `zathura` for viewing pdfs, and this is what I do and what I get:

* Open `[filename].tex` in `atom`
* Select `zathura` in `Opener` dropdown list 
* Compile (Ctrl+Alt+b)
* Get a `zathura` instance where the line I was on is highlighted (forward sync works)
* `ps` tells me I have the following opened (filenames redacted to ease reading)
```
/usr/bin/zathura --synctex-editor-command="/usr/lib64/electron-1.6/electron" "%{input}:%{line}" --synctex-forward=366:1:[filename (abs path)].tex [filename (abs path)].pdf
```
* "Ctrl + click" does not perform an inverse search.

In my own efforts to figure out what is wrong I tried with other pdf-viewers, and I found out something... strange is going on:

* I switch from `zathura` as `Opener`, and select `atril`, `zathura` opens. (this is even after restarting atom)
* Selecting `custom` as `Opener`, type `/usr/bin/atril`, `atril` opens (without any syntex-flags)

Let me know if you want a separate issue for this.

If I start `zathura` from a terminal, using the exact same syntax as `ps` supplies me with, I get that `zathura` refuse to start and it tells me
```
error: Too many arguments or missing filename while running with --synctex-forward
```

I tried to change to custom command as `Opener` again, but with `st -e zathura` as the custom command to see if I can get some error messages from `zathura`, but custom command seems to be called without synctex flags (because the syntax depends on the pdf-viewer I guess(?)).

Please let me know of possible ways to continue debugging this.

Other information: dist: Gentoo; `zathura`: 0.3.8; `atom`: 1.23.3; `atom-latex`: 0.50.0; `electron`: 1.6.16

**Comment by thomasjo** [comment]
@johanbluecreek It looks like you're using a custom build of Atom since version 1.23.3 ships with Electron 1.6.15. Would it be possible for you to try to reproduce the problem with the [latest official release](https://github.com/atom/atom/releases/latest) of Atom, which as of writing this is 1.29.0. Since you're on Gentoo I realize you have to build from source (or use some type of user-provided package system). Essentially I need to see if this is reproducible on an official, stable version of Atom.

Thanks for providing so many useful details! :bowing_man:

**Comment by johanbluecreek** [comment]
OK, testing with the official build, inverse search works. So I guess there is a bug/problem with how Gentoo builds atom or electron then. Thanks for helping me troubleshoot at least, and I suppose you can close this issue then. (and also thanks for an awesome and useful package!)

Thanks!
