### ISSUE TITLE
'Settings' button disappears

### ISSUE THREAD

**Issue by TimHe95** [thomasjo/atom-latex#516]
See below:
![](https://s3-ap-northeast-1.amazonaws.com/haochenhe-public/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7+2019-04-16+%E4%B8%8B%E5%8D%8812.25.47.png)

I install atom-latex as following:

`cd .atom/packages`

`git clone https://github.com/thomasjo/atom-latex.git`

`cd atom-latex` 

`npm install atom-latex`

Because i got error using `apm install atom-latex`

Or could you please tell me how can i change configurations?

Thank you for help.

**Comment by thomasjo** [comment]
If you want to install this package, you'll need to do `apm install latex` because this package is called `latex`. There's another Atom package called `atom-latex`. Sorry about the naming confusion.

Ensure you install the package properly using either `apm install latex`, or directly from within Atom. Be sure to completely remove the manually cloned repo first.

If the problem persist after installing the package via `apm` or Atom, please re-open the issue and share any potential errors shown in the _Developer Console_.
