### ISSUE TITLE
Use latexmk -pvc to continuously update

### ISSUE THREAD

**Issue by yurimalheiros** [thomasjo/atom-latex#52]
It would be nice an option to enable/disable the -pvc argument of latexmk, so the users could see the changes in the pdf viewer on the fly.

**Comment by thomasjo** [comment]
Since this requires the `latexmk` process to keep running, this is a non-trivial feature to implement given the current architecture. I agree that this would be a nice feature, so I will take a stab at this once I get time to finish implementing more pressing features (e.g. better UX around errors and warnings).

**Comment by yitzchak** [comment]
The build on save feature added in v0.31.0 effectively accomplishes this without resorting `-pvc`.
