### ISSUE TITLE
Opening result after successful build with Skim not working

### ISSUE THREAD

**Issue by niconaus** [thomasjo/atom-latex#551]
I've used this plugin for years, in combination with Skim. At some point, this stopped working. I get the following console error:

`An error occurred while trying to run "osascript -e "
set theLine to \"5\" as integer
...`

It goes on a bit longer, but doesn't let me copy paste. It just seems to be the body of the script.

Any ideas on what causes this?

**Comment by akosthekiss** [comment]
Same here. Things stopped working when I moved to an Apple M1-based machine. I have hacked some extra diagnostics into `ProcessManager.executeChildProcess` to see stdout and stderr in addition to the error code. What I got on stderr was "236:272: syntax error: Internal table overflow. (-2707)"

**Comment by akosthekiss** [comment]
A bit more detail:

```zsh
% osascript -e "
tell application \"/Applications/Skim.app\"
end tell
"

6:42: syntax error: Internal table overflow. (-2707)

% sw_vers 
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
% uname -msr
Darwin 21.3.0 arm64
```

**Comment by thomasjo** [comment]
@akosthekiss No problem! I was just about to link to the same issue myself.

@niconaus Make sure you are using Skim 1.6.9, which should have a fix for the issue you are experiencing. If you are still experiencing issues after upgrading, please re-open the issue.

For future reference, the problem is caused by so-called "synonyms" defined in the AppleScript dictionary. In the case of Skim, [removing two synonyms from `Skim.sdef`](https://sourceforge.net/p/skim-app/bugs/1438/?page=3#25bd/3b55/865d) should resolve the problem. The .sdef file is located inside the `Resources` folder in the application bundle.

**Comment by akosthekiss** [comment]
> I have hacked some extra diagnostics into `ProcessManager.executeChildProcess` to see stdout and stderr in addition to the error code.

One last note. It might be worth "officially" extending the error output of `ProcessManager.executeChildProcess` to help any potential future debugging.

**Comment by thomasjo** [comment]
> > I have hacked some extra diagnostics into `ProcessManager.executeChildProcess` to see stdout and stderr in addition to the error code.
> 
> One last note. It might be worth "officially" extending the error output of `ProcessManager.executeChildProcess` to help any potential future debugging.

@akosthekiss That is an excellent idea. Would you mind opening a separate feature request issue for that?
