### ISSUE TITLE
AppVeyor builds not working

### ISSUE THREAD

**Issue by nscaife** [thomasjo/atom-latex#66]

**Comment by thomasjo** [comment]
Believe the first broken spec can be fixed by something like this

``` coffee
describe "initialize", ->
  it "initializes all properties", ->
    opener = helpers.nullOpener()
    spyOn(latex, 'resolveOpenerImplementation').andReturn(opener.constructor)
    latex.initialize()

    expect(latex.builder).toBeDefined()
    expect(latex.logger).toBeDefined()
    expect(latex.opener).toBeDefined()
```

Going to spin up my Windows VM and verify.

**Comment by thomasjo** [comment]
Found the bug... forgot to remove `helpers.overridePlatform('darwin')` from one of the specs during refactoring: [latex-spec.coffee#L87](https://github.com/thomasjo/atom-latex/blob/192eab770107f5b9369fcb096fb277953d96136d/spec/latex-spec.coffee#L87)

**Comment by thomasjo** [comment]
AppVeyor is such an unstable platform. Most builds fail like this:
https://ci.appveyor.com/project/thomasjo/atom-latex/build/201#L7777

It's likely a combination of Chocolatey and AppVeyor, but difficult to track down since I have no means of inspecting the build environment. Perhaps it'd be better to download the latest ZIP-ed release instead of relying on Chocolatey... :thought_balloon:

**Comment by thomasjo** [comment]
Had to re-launch the build a few times to make it green. I need to find an alternative to AppVeyor.
