### ISSUE TITLE
Set Master document for compile

### ISSUE THREAD

**Issue by Maladus** [thomasjo/atom-latex#70]
Select a master document for compile big Project.
That i can work on a include tex file, but the master.tex will compiled.

**Comment by ajclarke90** [comment]
+1 - Would love this for my Thesis writing.

**Comment by Fania** [comment]
+1 Same.

**Comment by thomasjo** [comment]
I guess I really need to start writing some documentation soon — this functionality is already supported via "magic comments" (first introduced in TeXShop I believe). Simply add something like this to the top of your child files
```
% !TEX root = master.tex
```

The whitespace in front of `!TEX` and around the equal sign is optional. With the magic comment in place, invoking the *Build* command will build the root/master file instead of the current file. If any of you have ideas for improvements or what not, don't be shy!

---
Complete *MWE* for good measure:

**master.tex**
``` tex
\documentclass[a4paper]{scrartcl}

\begin{document}
    \include{a}
    \include{b}
\end{document}
```

**a.tex**
``` tex
% !TEX root = master.tex

\section{This is a.tex}
...
```

**b.tex**
``` tex
% !TEX root = master.tex

\section{and this is b.tex}
Seems to work!
```

**Comment by ajclarke90** [comment]
Awesome. Thanks @thomasjo

**Comment by Maladus** [comment]
Nice, Thank you
