### ISSUE TITLE
Clean should only remove temp files

### ISSUE THREAD

**Issue by louiscpalma** [thomasjo/atom-latex#75]
The clean button currently deletes all files generated when compiling the *.tex file, including the pdf. It would make much more sense to leave the pdf (since it breaks the atom pdf viewer package) for writers' reference and it will get overwritten on re-compile anyway. Clean can just be used to remove the disorganization from the directory.
.

**Comment by nscaife** [comment]
IIRC, this did not previously break pdf-view (though I have since moved on to Sumatra).  I'm curious what changed, if anything.

My use case needs the PDF to be deleted during clean.  My original intent was to remove everything that the compiler generates, including the PDF, so that the directory contains nothing but source content afterwards.

There's a configuration option currently in the package to override the cleaned extensions list.  Can you remove the PDF extension from the list?  This _might_ be better as a "also remove output PDF" checkbox, instead of requiring the user to respecify the entire list.

**Comment by thomasjo** [comment]
As @nscaife has mentioned, a (temporary) workaround is to override the the *Clean Extensions* option. Sadly Atom doesn't support additive changes to options, so you'll have to specify the full list **minux** `.pdf`. Either set it via the settings view, or add something like this to your `~/.atom/config.cson` file

```cson
"*":
  # ...
  latex:
    cleanExtensions: [
      '.aux'
      '.bbl'
      '.blg'
      '.fdb_latexmk'
      '.fls'
      '.log'
      '.out'
    ]
  # ...
```

As for changing the current behavior, we could either change the default extensions list, add a checkbox as per @nscaife's suggestion, or perhaps an enum. If going the enum route, I think it'd make sense to perhaps move away from an extension list with default values, and instead provide that as a *Custom* option, but not entirely sure.

**Comment by louiscpalma** [comment]
User configuration is always preferred! Just seemed like it should have been a default behavior.
