### ISSUE TITLE
No such file composer.coffee

### ISSUE THREAD

**Issue by FlyingPumba** [thomasjo/atom-latex#86]
Hi, using version 24.0 of latex package on Atom version 0.201.0 On a fresh Ubuntu 14.04.
When pressing Ctlr-Alt-B it does nothing. The Developer Console yields: 
```
Uncaught TypeError: Cannot read property 'constructArgs' of undefined
/home/user/.atom/packages/latex/lib/composer.coffee:35 module.exports.Composer.buildmain.js:12
latexBuild/usr/share/atom/resources/app.asar/src/command-registry.js:238 
module.exports.CommandRegistry.handleCommandEvent/usr/share/atom/resources/app.asar/src/command-registry.js:3
(anonymous function)/usr/share/atom/resources/app.asar/src/command-registry.js:153 
module.exports.CommandRegistry.dispatch/usr/share/atom/resources/app.asar/src/window-event-handler.js:71
(anonymous function)events.js:77 emitOneevents.js:166 emit

/usr/share/atom/resources/app.asar/src/atom.js:221
Uncaught Error: ENOENT: no such file or directory, open '/home/user/.atom/packages/latex/lib/composer.coffee'
```

**Comment by thomasjo** [comment]
Are you able to reliably reproduce this? Even after completely closing all instances of Atom?

**Comment by thomasjo** [comment]
My thinking is that this was caused by a bug in Node/Atom related to module's being cached incorrectly. Thing is, there's no such file as `composer.coffee` anymore, since I migrated away from CoffeeScript to ES6/Babel for the implementation of package.

If my hypothesis is correct, your problem should be resolved by simply restarting Atom.

**Comment by FlyingPumba** [comment]
@thomasjo You were right ! closing and re-opening fixed the issue.
Thanks.
