### ISSUE TITLE
Cannot compile with miktex

### ISSUE THREAD

**Issue by noirchen** [thomasjo/atom-latex#92]
I tried with miktex on windows, with the path pointed to the latex bin since I installed miktex in a customized location. When I run compile, nothing happens, and no log file is generated. Atom shows "latex compilation error", but there is no useful information. But I can compile using other editor like texstudio with the same path configuration.

**Comment by nscaife** [comment]
Is Perl installed and in the Windows path?

**Comment by noirchen** [comment]
No. Is it because latexmk requires perl?

**Comment by nscaife** [comment]
Yes -- MikTeX's `latexmk` requires Perl.  If you can run latexmk at a Windows command prompt, Atom should have no problem running it.

**Comment by noirchen** [comment]
OK I see. Miktex has another engine, `texify`, which is a native command line utility. I think it is possible to use this instead of `latexmk` to do the compilation.

**Comment by nscaife** [comment]
I'm not sure about using another engine.  I used MikTeX for a while and switched to TeX Live because it was less hassle to set up with Atom on a fresh system.

@thomasjo might know more about how to configure alternate engines!

**Comment by thomasjo** [comment]
@noirchen For the foreseeable future, this package will only support `latexmk`. If someone submits a PR that adds optional support for `texify` building (and/or similar), that is a swap-in for the current default builder, then that will almost certainly get merged. The package is architected in such a way to support other builders, it just isn't worth my time and effort to implement others right now.

Since @nscaife has already pointed out the solution to your specific problem, I'm going to close this issue.

---
*NOTE: Implementing another builder, most likely means implementing a new log parser as well.*

**Comment by thomasjo** [comment]
Just wanted to let interested parties know that #98 adds support for `texify`, and I'm preparing a new release right now. Huge thanks to @yorugac!
